export const authConstance = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SINING_REQUEST: "SINING_REQUEST",
  SINING_SUCCESS: "SINING_SUCCESS",
  SINING_FAILURE: "SINING_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const menuConstance = {
  CREATE_MENU_REQUEST: "CREATE_MENU_REQUEST",
  CREATE_MENU_SUCCESS: "CREATE_MENU_SUCCESS",
  CREATE_MENU_FAILURE: "CREATE_MENU_FAILURE",
  GET_MENU_REQUEST: "GET_MENU_REQUEST",
  GET_MENU_SUCCESS: "GET_MENU_SUCCESS",
  GET_MENU_FAILURE: "GET_MENU_FAILURE",
  DELETE_MENU_REQUEST: "DELETE_MENU_REQUEST",
  DELETE_MENU_SUCCESS: "DELETE_MENU_SUCCESS",
  DELETE_MENU_FAILURE: "DELETE_MENU_FAILURE",
  GET_FOOD_BY_MENU_ID_REQUEST: "GET_FOOD_BY_MENU_ID_REQUEST",
  GET_FOOD_BY_MENU_ID_SUCCESS: "GET_FOOD_BY_MENU_ID_SUCCESS",
  GET_FOOD_BY_MENU_ID_FAILURE: "GET_FOOD_BY_MENU_ID_FAILURE",
};
export const foodConstance = {
  CREATE_FOOD_REQUEST: "CREATE_FOOD_REQUEST",
  CREATE_FOOD_SUCCESS: "CREATE_FOOD_SUCCESS",
  CREATE_FOOD_FAILURE: "CREATE_FOOD_FAILURE",
  GET_FOOD_REQUEST: "GET_FOOD_REQUEST",
  GET_FOOD_SUCCESS: "GET_FOOD_SUCCESS",
  GET_MENU_FAILURE: "GET_MENU_FAILURE",
  GET_FOOD_BY_SORT_REQUEST: "GET_FOOD_BY_SORT_REQUEST",
  GET_FOOD_BY_SORT_SUCCESS: "GET_FOOD_BY_SORT_SUCCESS",
  GET_MENU_BY_SORT_FAILURE: "GET_MENU_BY_SORT_FAILURE",
};
export const offersConstance = {
  CREATE_OFFERS_REQUEST: "CREATE_OFFERS_REQUEST",
  CREATE_OFFERS_SUCCESS: "CREATE_OFFERS_SUCCESS",
  CREATE_OFFERS_FAILURE: "CREATE_OFFERS_FAILURE",
  GET_OFFERS_REQUEST: "GET_OFFERS_REQUEST",
  GET_OFFERS_SUCCESS: "GET_OFFERS_SUCCESS",
  GET_OFFERS_FAILURE: "GET_OFFERS_FAILURE",
};
export const cartConstance = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",
  GET_TO_CART: "GET_TO_CART",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
};
export const orderConstance = {
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
};
