export const authConstance = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SINING_REQUEST: "SINING_REQUEST",
  SINING_SUCCESS: "SINING_SUCCESS",
  SINING_FAILURE: "SINING_FAILURE",
};
